config/routes.rb
Importrequire::Application.routes.draw do

	match "register" => "User#create", :as => "register"
	match "logout" => "welcome#logout", :as => "logout"
	match "login" => "welcome#login", :as => "login"
	match "search" => "search#search", :as => "search"
	match "help" => "help#help", :as => "help"
  match "inbox" => "message#inbox", :as =>"inbox"
  match "inbox/compose" => "message#compose", :as =>"compose"
  match "inbox/compose/:handle" => "message#compose", :as =>"compose_to"
  match "inbox/create_mail" => "message#create_mail", :as =>"create_mail"
  match "inbox/:mid" => "message#view", :as =>"view_mail"
  match "inbox/:mid/reply" => "message#reply", :as =>"reply_mail"
  match "inbox/:mid/unread" => "message#unread", :as =>"unread_mail"
  match "inbox/:mid/delete" => "message#delete", :as =>"delete_mail"
	match ":handle/works/:wid/rate/:rating" => "User#rate_work", :as => "user_rate_work"
	match ":handle/works/create_work" => "User#create_work", :as => "user_create_work"
	match ":handle/works/remove_work/:wid" => "User#remove_work", :as => "user_remove_work"
	match ":handle/works/edit_work/:wid" => "User#edit_work", :as => "user_edit_work"
	match ":handle/works" => "User#works", :as => "user_works"
	match ":handle/edit/create_affil" => "User#create_affil", :as => "user_create_affil"
	match ":handle/edit/remove_affil/:name" => "User#remove_affil", :as => "user_remove_affil"
	match ":handle/edit/create_tag" => "User#create_tag", :as => "user_create_tag"
	match ":handle/edit/remove_tag/:id" => "User#remove_tag", :as => "user_remove_tag"
	match ":handle/edit/remove_all_tags" => "User#remove_all_tags", :as => "user_remove_all_tags"
	match ":handle/tags" => "User#edit_tags", :as => "user_tags"
	match ":handle/edit" => "User#edit", :as => "user_edit"
	match ":handle" => "User#view", :as => "user_name"

   root :to => "welcome#index"

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  def inbox
    if session[:user]
      @user = User.where(:handle => session[:user])[0]
      @messages = @user.messages
    else
      @user = nil
    end
  end

  def view
    message = Message.where(:id => params[:mid])[0]
    if !message.nil?
      if !session[:user].nil?
        u = User.where(:handle => session[:user])[0]
        if message.to_id == u.id
          @message = message
          @to = u.handle
          @from = User.where(:id => message.from_id)[0].handle
          if !@message.read
            @message.read = true
            @message.save
          end
        end
      end
    end

  end

  def compose
    if session[:user]
      @user = User.where(:handle => session[:user])[0]
      if params[:handle]
        @to = params[:handle]
      end
    else
      @user = nil
    end
  end

  def reply
    message = Message.where(:id => params[:mid])[0]
    if !message.nil?
      if !session[:user].nil?
        user = User.where(:handle => session[:user])[0]
        if message.to_id == user.id
          @user = user
          @old_message = message
          @to = User.where(:id => message.from_id)[0].handle
          @subject = "RE:" + message.subject
          @body = "\r\n \r\n=== Previous message begins here ===\r\n" + message.body
        end
      end
    end
    render :action => "compose"
  end

  def create_mail
    if !session[:user].nil?
      @user = User.where(:handle => session[:user])[0]
      @to = params[:to]
      @subject = params[:subject]
      @body = params[:body]
    
      if @to == "" or @body == "" or @subject == ""
       flash[:notice] = "Remember to fill in all the fields"
       else
         to_user = User.where(:handle => @to)[0]
         if to_user.nil?
           flash[:notice] = "Unrecognised user"
         else
           message = Message.new
           message.to_id = to_user.id
           message.from_id = @user.id
           message.subject = @subject
           message.body = @body

           message.save

           to_user.messages << message
           to_user.save

           #TODO Notify email
            redirect_to :action => "inbox" and return
         end
      end
    end
    render :action => "compose"
  end

  def delete
    message = Message.where(:id => params[:mid])[0]
    if !message.nil?
      if !session[:user].nil?
        u = User.where(:handle => session[:user])[0]
        if message.to_id == u.id
          @user = u
          @message = message
          @message.destroy
        end
      end
    end  
    redirect_to :action => "inbox" 
  end

  def unread
    message = Message.where(:id => params[:mid])[0]
    if !message.nil?
      if !session[:user].nil?
        u = User.where(:handle => session[:user])[0]
        if message.to_id == u.id
          @user = u
          @message = message
          @message.read = false
          @message.save
        end
      end
    end  
    redirect_to :action => "inbox" 
  end
end

app/helpers/message_helper.rb
module MessageHelper
end

app/views/message/_messagelist.html.erb
<% if messages.length < 1 %>
  <em>No messages</em>
<% else %>
  <table id="innermessagelist">
      <tr>
          <th class="message_from">From</th>
          <th class="message_subject">Subject</th>
          <th class="message_controls">Actions</th>
        </div>
      </tr>  
    <% messages.each do |m| 
        from = User.where(:id => m.from_id)[0]
        to = User.where(:id => m.to_id)[0]
    %>
      <tr>
          <td class="message_from <%="read" if !m.read%>"><%=from.handle%></td>
          <td class="message_subject <%="read" if !m.read%>"><%=link_to m.subject, view_mail_path(m.id), :class =>
          "white"%></td>
          <td class="message_controls"><%= link_to "Reply", reply_mail_path(m.id), :class => "white"%> 
          | 
  <%= link_to "Delete", delete_mail_path(m.id), :class => "white", :confirm => "Are you sure?" %>
          |
  <%= link_to "Unread", unread_mail_path(m.id), :class => "white" %>
          </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/message/compose.html.erb
<% if !@user.nil? %>
  <%= link_to "<-- Back to inbox", inbox_path, :class => "white" %>
  <h2>Compose</h2>
  <div id="compose_form">
  <%= form_tag({:action => :create_mail}, :method => "poat") %>
    <span id="compose_to">To: <%= text_field_tag :to, @to %></span>
    <span id="compose_subject">Subject: <%= text_field_tag :subject, @subject %></span>
    <span id="compose_body">Message: <span id="compose_body_padding"><%= text_area_tag :body, @body %></span></span>
    <%= submit_tag "Send" %>
  </form>
  </div>
<% else %>
  <em>You have come here in error</em>
<% end %>

app/views/message/inbox.html.erb
<% if !@user.nil? %>
  <h2>Inbox</h2>
  <div id="inbox_controls">
    <%= link_to "Compose", compose_path(), :class => "white" %>
  </div>
  <div id="inbox_list">
    <%= render :partial => "messagelist", :locals => {:messages => @messages} %>
  </div>
<% else %>
  <em>You have come here in error</em>
<% end %>

app/views/message/view.html.erb
<% if @message %>
  <%= link_to "<-- Back to inbox", inbox_path, :class => "white" %>
  <div id="message_details">
    <span id="message_view_from"><p>From: <%=@from%></p></span>
    <span id="message_view_subject"><p>Subject: <%=@message.subject%></p></span>
    <span id="message_view_body">Message: <pre><%=@message.body%></pre></span>
  </div>
	<div id="view_controls">
		<%= link_to "Reply", reply_mail_path(@message.id), :class => "white" %>
		|
		<%= link_to "Delete", delete_mail_path(@message.id), :class => "white", :confirm => "Are you sure?" %>
	</div>
<% else %>
  <em>You have come here in error</em>
<% end %>