config/routes.rb
Importrequire::Application.routes.draw do

	match "register" => "User#create", :as => "register"
	match "logout" => "welcome#logout", :as => "logout"
	match "login" => "welcome#login", :as => "login"
	match "search" => "search#search", :as => "search"
	match "help" => "help#help", :as => "help"
  match "inbox" => "message#inbox", :as =>"inbox"
  match "inbox/compose" => "message#compose", :as =>"compose"
  match "inbox/compose/:handle" => "message#compose", :as =>"compose_to"
  match "inbox/create_mail" => "message#create_mail", :as =>"create_mail"
  match "inbox/:mid" => "message#view", :as =>"view_mail"
  match "inbox/:mid/reply" => "message#reply", :as =>"reply_mail"
  match "inbox/:mid/unread" => "message#unread", :as =>"unread_mail"
  match "inbox/:mid/delete" => "message#delete", :as =>"delete_mail"
	match ":handle/works/:wid/rate/:rating" => "User#rate_work", :as => "user_rate_work"
	match ":handle/works/create_work" => "User#create_work", :as => "user_create_work"
	match ":handle/works/remove_work/:wid" => "User#remove_work", :as => "user_remove_work"
	match ":handle/works/edit_work/:wid" => "User#edit_work", :as => "user_edit_work"
	match ":handle/works" => "User#works", :as => "user_works"
	match ":handle/edit/create_affil" => "User#create_affil", :as => "user_create_affil"
	match ":handle/edit/remove_affil/:name" => "User#remove_affil", :as => "user_remove_affil"
	match ":handle/edit/create_tag" => "User#create_tag", :as => "user_create_tag"
	match ":handle/edit/remove_tag/:id" => "User#remove_tag", :as => "user_remove_tag"
	match ":handle/edit/remove_all_tags" => "User#remove_all_tags", :as => "user_remove_all_tags"
	match ":handle/tags" => "User#edit_tags", :as => "user_tags"
	match ":handle/edit" => "User#edit", :as => "user_edit"
	match ":handle" => "User#view", :as => "user_name"

   root :to => "welcome#index"

end

app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :affiliations
	has_and_belongs_to_many :tags
	has_and_belongs_to_many :works
  has_many :ratings
  has_many :messages, :foreign_key => "to_id"
	validates :handle, :presence => true, :uniqueness => true
	validates :email, :presence => true, :uniqueness => true
	validates :passhash, :presence => true
end

app/controllers/user_controller.rb
require_dependency 'password'
require_dependency 'search'
require_dependency 'rate'
require 'uri'

class UserController < ApplicationController

	before_filter :validate_params, :only => :create
	before_filter :validate_edit_params, :only => :edit

  def restricted_name(handle)
    return ["inbox", "search", "register", "login", "logout"].include?(handle)
  end

  def validate_edit_params

		@old_params = params
    @validated = false
    if params[:pass]

      user = User.where(:handle => session[:user])[0]
        
      #Means they are editing, first off check password
      pass1 = Password.hash(params[:pass], user[:salt]);
      if pass1 == user[:passhash]
        @validated = true
      else
				flash[:notice] = "Incorrect password"
      end
    end

  end

	# Checks the form is filled correctly
	def validate_params

		@old_params = params
		# Just gets form parameters
		v_params = params.clone
		v_params.delete_if {|k,v| ["action","controller"].include?(k) }
		@validated = false
    warn = ""
		if v_params != {}

			# Verification for all filled in
			empty = false
      v_params.each { |k,v| empty = true if v == "" }
			if(empty)
				warn += "Please fill in all fields - "
			end

			# Check emails and passwords match
			if(v_params[:pass1] != v_params[:pass2])
				warn += "Passwords do not match - "
			end
			if(v_params[:email] != params[:cemail])
				warn += "Emails do not match - "
			end
      if restricted_name(params[:handle])
        # Made sure it is not the name of a page
				warn += "Handle in use by system - "
      end
			if(warn.size > 0)
        flash[:notice] = warn
				render :action => :create and return
			end
			@validated = true;
		end
	end

	# Checks the form is filled correctly
	def validate_work_params

		@old_params = params
		# Just gets form parameters
		v_params = params.clone
		v_params.delete_if {|k,v| ["action","controller","handle"].include?(k) }
		@validated = false
		if v_params != {}

			# Verification for all filled in
			empty = false
      v_params.each { |k,v| empty = true if v == "" }
			if(empty)
				flash[:notice] = "Please fill in all fields - "
			else
				@validated = true;
			end
			if(flash[:notice])
				render :edit => :create and return
			end
		end
		return v_params == {}
	end

  def create
		if @validated
			u = User.new
      u.name 					= params[:name]
      u.handle 				= params[:handle]
      u.email 				= params[:email]
      u.showname 			= (params[:showname]) ? true : false;
      u.showemail 		= (params[:showemail]) ? true : false;
      u.notify 				= (params[:notify]) ? true : false;
			s = Password.salt()
      u.passhash 			= Password.hash(params[:pass1],s)
      u.salt 					= s

			suc = verify_recaptcha && u.save
			flash[:notice] 	= suc

			if(suc)
        NewUserMailer.welcome_user(u).deliver if u.notify
				Search.buildUserSearchString(u)
				session[:user] = u[:handle]
				redirect_to :controller => :welcome, :action => :index and return
			else
				@errors = u.errors
				render :action => :create
			end

		end
  end

  def edit
    if session[:user]
      if session[:user] == params[:handle]
        @user = User.where(:handle => session[:user])[0]
        if @validated
          u = @user
          u.name 					= params[:name]
          u.email 				= params[:email]
          u.showname 			= (params[:showname]) ? true : false;
          u.showemail 		= (params[:showemail]) ? true : false;
          u.notify 				= (params[:notify]) ? true : false;
          u.save
          flash[:notice] 	= "Information successfully updated"
        end
      end
    end
  end

  def view
		if(session[:user] && !params[:handle])
			@vuser = User.where(:handle => session[:user])[0]
		end
		if params[:handle]
			vusers = User.where(:handle => params[:handle])[0]
			@vuser = vusers
		end
  end

  def create_affil
    @user = User.where(:handle => session[:user])[0]
    if params[:affiliation] != ""
      # See if already exists, if so, use it
      af = Affiliation.where(:name => params[:affiliation])
      if af.length == 0
        af = Affiliation.new
        af.name = params[:affiliation]
        af.save
      else
        af = af[0]
      end

      # Add to user
      @user.affiliations << af if !@user.affiliations.include?(af)
      @user.save
			Search.buildUserSearchString(@user)

    end
    respond_to do |format|
      format.js 
    end  
  end

  def remove_affil
    @user = User.where(:handle => session[:user])[0]
    if params[:name] != ""
      af = Affiliation.where(:name => params[:name])
      if af.length > 0
        af = af[0]
        @user.affiliations.delete(af) if @user.affiliations.include?(af)
      @user.save
			Search.buildUserSearchString(@user)
      end
    end

    respond_to do |format|
      format.js {render :action => :create_affil} 
    end  
  end

  def works
    if session[:user]
      if session[:user] == params[:handle]
        @user = User.where(:handle => session[:user])[0]
				validated = validate_work_params()
        if @validated
          w = Work.new
          w.name 					= params[:name]
          w.description 	= params[:description]
          w.url 					= params[:url]
          w.save
          if params[:tags] != ""
            tags = []
            params[:tags].split(",").each do |tt|
              if tt != ""
                # See if already exists, if so, use it
                t = Tag.where(:name => tt)
                if t.length == 0
                  t = Tag.new
                  t.name = tt
                  t.save
                else
                  t = t[0]
                end
                tags << t
              end
            end

            # Add to work
            tags.each do |t|
              w.tags << t if !w.tags.include?(t)
            end
            w.save
            Search.buildWorkSearchString(w)
          end
					@user.works << w
					@user.save
					Search.buildUserSearchString(@user)
          flash[:notice] 	= "Information successfully updated"
        end
      end
    end
  end

  def remove_work
    @user = User.where(:handle => session[:user])[0]
    if params[:wid] != ""
      af = Work.where(:id => params[:wid])
      if af.length > 0
        af = af[0]
        @user.works.delete(af) if @user.works.include?(af)
        @user.save
        if af.users.size == 0
          af.delete
        end
			Search.buildUserSearchString(@user)
      end
    end

    respond_to do |format|
      format.js {render :action => :create_work} 
    end  
  end

  def edit_work
    @user = User.where(:handle => session[:user])[0]
    @af = nil
    if params[:wid] != ""
      @af = Work.where(:id => params[:wid])
      if @af.length > 0
        @af = @af[0]
      end
      # Edit if params exist
      if params[:name] and params[:url] and params[:description]
				validated = validate_work_params()
        if @validated
          w = @af
          w.name 					= params[:name]
          w.description 	= params[:description]
          w.url 					= params[:url]
          if params[:tags] != ""
            tags = []
            params[:tags].split(",").each do |tt|
              if tt != ""
                # See if already exists, if so, use it
                t = Tag.where(:name => tt)
                if t.length == 0
                  t = Tag.new
                  t.name = tt
                  t.save
                else
                  t = t[0]
                end
                tags << t
              end
            end

            # Add to work
            w.tags = []
            tags.each do |t|
              w.tags << t if !w.tags.include?(t)
            end
            w.save
            Search.buildWorkSearchString(w)
          end
          w.save
					@user.save
					Search.buildUserSearchString(@user)
          @af = w
          flash[:notice] 	= "Information successfully updated"
        end
      end
    end
  end

  def edit_tags
    @user = User.where(:handle => session[:user])[0]
  end

  def create_tag
    @user = User.where(:handle => session[:user])[0]
    if params[:tag] != ""
      tags = []
      params[:tag].split(",").each do |tt|
        if tt.strip != ""
          # See if already exists, if so, use it
          t = Tag.where(:name => tt)
          if t.length == 0
            t = Tag.new
            t.name = URI.escape(tt)
            t.save
          else
            t = t[0]
          end
          tags << t
        end
      end

      # Add to user
      tags.each do |t|
        @user.tags << t if !@user.tags.include?(t)
      end
      @user.save
			Search.buildUserSearchString(@user)

    end
    respond_to do |format|
      format.js 
    end  
  end

  def remove_tag
    @user = User.where(:handle => session[:user])[0]
    if params[:id] != ""
      t = Tag.where(:id => params[:id])
      if t.length > 0
        t = t[0]
        @user.tags.delete(t) if @user.tags.include?(t)
      @user.save
			Search.buildUserSearchString(@user)
      end
    end

    respond_to do |format|
      format.js {render :action => :create_tag} 
    end  
  end

  def remove_all_tags
    @user = User.where(:handle => session[:user])[0]
    @user.tags = [] 
    @user.save
		Search.buildUserSearchString(@user)
    respond_to do |format|
      format.js {render :action => :create_tag} 
    end  
  end

	def rate_work

		work = Work.where(:id => params[:wid])[0]
    @user = User.where(:handle => session[:user])[0]
    @vuser = work.users[0] 
		rating = params[:rating]
		r = Rating.where(:work_id => params[:wid], :user_id => @user.id)

		# See if has a current rating
		if r.length == 0
			r = Rating.new
		else
			r = r[0]
		end
			
		# Get weight
		weight = Rate::calculate_weight(@user, work)

		#r.work_id = work.id
		#r.user_id = @user.id
		r.weight = weight
		r.score = rating

		work.ratings << r
		@user.ratings << r

		work.save
		@user.save
		r.save

		Rate::calculate_rating(work)

    respond_to do |format|
      format.js {render :action => :rate_work} 
    end  
	end

app/helpers/user_helper.rb
module UserHelper
  
end

app/views/user/_affillist.html.erb
<% if affiliations.length < 1 %>
  <em>No affiliations listed</em>
<% else %>
  <table>
    <% affiliations.each do |af| %>
    <tr>
      <td><%= af[:name] %></td>
      <td><%= link_to "remove", 
              user_remove_affil_path(:handle => session[:user],
                                     :name => af[:name]),
              :remote => true%></td>
    </tr>
    <% end %>
  </table>
<% end %>

app/views/user/_taglist.html.erb
<% require 'uri' %>
<% if tags.length < 1 %>
  <em>No tags listed</em>
<% else %>
  <table>
    <% tags.each do |t| %>
    <tr>
      <td><%= URI::unescape(t[:name]) %></td>
      <td><%= link_to "remove", 
              user_remove_tag_path(:handle => session[:user],
                                     :id => t[:id]),
              :remote => true%></td>
    </tr>
    <% end %>
  </table>
<% end %>

app/views/user/create.html.erb
<% 
# Extra column needed?
ec = false;
if @errors != nil 
	ec = true
end
%>

<div id="reg_form">
<h2>User Registration</h2>
<br/>
<%= form_tag({:action => :create}, :method => "post")  %>
<table>
	<tr><td>Name:</td><td><%= text_field_tag :name, @old_params[:name] %></td><td><em><%= (ec && @errors[:name] != []) ? @errors[:name] : "" %></em></td></tr>
	<tr><td>Handle:</td><td><%= text_field_tag :handle, @old_params[:handle] %></td><td><em><%=(ec && @errors[:handle] != []) ? @errors[:handle] : "" %></em></td></tr>
	<tr><td>Email:</td><td>  <%= text_field_tag :email, @old_params[:email] %></td><td><em><%= (ec && @errors[:email] != []) ? @errors[:email] : "" %></em></td></tr>
	<tr><td>Confirm Email:</td><td>  <%= text_field_tag :cemail, @old_params[:cemail] %></td><td></td></tr>
	<tr><td>Show Name?:</td><td> <%= check_box_tag :showname, @old_params[:showname] %></td><td></td></tr>
	<tr><td>Show Email?:</td><td> <%= check_box_tag :showemail, @old_params[:showemail] %></td><td></td></tr>
	<tr><td>Recieve Notifications?:</td><td> <%= check_box_tag :notify, @old_params[:notify] %></td><td></td></tr>
	<tr><td>Password:</td><td> <%= password_field_tag :pass1 %></td><td></td></tr>
	<tr><td>Confirm Password:</td><td> <%= password_field_tag :pass2 %></td><td></td></tr>
</table>
<div id="recaptcha">
<%= recaptcha_tags :display => {:theme => "white"}%>
</div>
<p>By signing up to this website you are hereby agreeing to not be an idiot and to treat this site, other users, and yourself with dignity and respect.</p>
<%= submit_tag "Register", :class =>"button" %>
</form>
</div>

app/views/user/edit.html.erb
<% require_dependency 'gravatar' %>

<% if @user %>
<%= link_to "<-- Back to Profile", user_name_path(@user[:handle]), :class =>"back"  %>
<div id="edit">
  <h2> Edit Information </h2>

  <div id="userav">
    <h3>Avatar</h3>
    <img src="<%= Gravatar.getAvatarURL(@user[:email]) %>" />
    <p>Want to change this avatar? Import::require uses <a href="http://www.gravatar.com">Gravatar</a>. Navigate there to
    see how to change yours. They're pretty cool.</p>
  </div>


  <div id="usereditform">
    <h3>Contact and Privacy</h3>
  <%= form_tag({:action => :edit}, :method => "post") %>
  <table>
    <tr>
      <td>Name:</td><td><%= text_field_tag :name, @user[:name] %></td>
    </tr>
    <tr>
      <td>Email:</td><td> <%= text_field_tag :email, @user[:email] %></td>
    </tr>
    <tr>
      <td>Show Name?:</td><td><%= check_box_tag :showname, true, @user[:showname] %></td>
    </tr>
    <tr>
      <td>Show Email?:</td><td><%= check_box_tag :showemail,true, @user[:showemail] %></td>
    </tr>
    <tr>
      <td>Recieve Notifications?:</td> <td><%= check_box_tag :notify, true, @user[:notify] %></td>
    </tr>
    <tr>
      <td colspan="2">Please enter your password to verify the changes made.</td>
    </tr>
    <tr>  
	    <td>Password:</td><td> <%= password_field_tag :pass %></td>
    </tr>
  </table>
  <br/>
  <%= submit_tag "Update" %>

  </form>
  </div>

  <div id="affileditform">
    <h3>Affiliations</h3>
    <div id="affillist">
      <%= render :partial => "affillist", :locals => {:affiliations => @user.affiliations} %>
    </div>
    <%= form_tag(  url_for( :action => :create_affil), :remote => true) %>
    <table><tr>
    <td>Add new Affiliation</td><td><%= text_field_tag :affiliation %> </td>
    </tr></table>
    <%= submit_tag "Add" %>
    </form>
  </div>
</div>

<% else %>
<em>You have come here in error</em>
<% end %>

app/views/user/edit_tags.html.erb
<% if @user %>
<%= link_to "<-- Back to Profile", user_name_path(@user[:handle]), :class => "back"  %>
<div id="edit_tags">
  <h2> Edit Tags </h2>

    <p>Enter tags here that describe your programming experience.</p>
    <em>These will not be publically shown but will further
    aid in indexing your profile for more accurate searching.</em>
    <p/>

  <div id="tageditform">
    <h3>Tags</h3>
    <div id="taglist">
      <%= render :partial => "taglist", :locals => {:tags => @user.tags} %>
    </div>
    <%= form_tag(  url_for( :action => :create_tag), :method => "post", :remote => true) %>
    <table><tr>
    <td>Add new tag [commas for multiple tags]</td><td><%= text_field_tag :tag %> </td>
    </tr></table>
    <%= submit_tag "Add" %>
    <%= link_to "remove all tags", 
            user_remove_all_tags_path(:handle => session[:user]),
            :remote => true,
            :confirm => "Are you sure?",
						:class => "white" %>
    </form>
  </div>
</div>

<% else %>
<em>You have come here in error</em>
<% end %>

app/views/user/edit_work.html.erb
<% if @af %>
	<%= link_to "<-- Back to Works", user_works_path(@user[:handle]), :class => "back"  %>

	<div id="editworks">
	<h3>Edit work</h3>

	<div id="workeditform">
		<%= form_for  @af, :as => :af, :url => {:action => :edit_work} do |f| %>
			<table>
				<tr><th colspan="2">Edit Work</th></tr>
				<tr><td>Name:</td><td><%= text_field_tag :name, @af.name %> </td></tr>
				<tr><td>URL:</td><td><%= text_field_tag :url, @af.url %> </td></tr>
				<tr><td>Decription:</td><td><%= text_area_tag :description, @af.description%> </td></tr>
        <% 
        tag_str = ""
        @af.tags.each{ |t| tag_str << "#{t.name},"}
        tag_str = tag_str.slice(0, tag_str.size-1)
        %>
				<tr><td>Tags:</td><td><%= text_field_tag :tags, tag_str%> </td></tr>
			</table>
			<%= submit_tag "Add" %>
      <% end %>
	</div>
</div>
<% else %>
	<em>You have come here in error</em>
<% end %>

app/views/user/view.html.erb
<% require_dependency 'gravatar' %>
<% if @vuser %>
	<div id="user">
		<div id="infobox">
			<div id="userav">
				<img src="<%= Gravatar.getAvatarURL(@vuser[:email]) %>" />
			</div>
			<div id="userinfo">
				<h3>Info</h3>
				<ul>
					<% if @vuser[:showname] %>
					<li>Name: <%= @vuser[:name]%></li>
					<% end %>
					<li>Handle: <%= @vuser[:handle]%></li>
					<% if @vuser[:showemail] %>
					<li>Email: <%= @vuser[:email]%></li>
					<% end %>
					<% if @vuser.affiliations.length > 0 %>
					<li>Affliations:</li>
					<ul>
						<% @vuser.affiliations.each do |affil| %>
							<li><%= affil.name %></li>
						<% end %>
					</ul>
					<% end %>
				</ul>
			</div>
			<div id="menubox">
        <% if session[:user] %>
				<h3>Menu</h3>
				<ul>
					<% if @vuser[:handle] == session[:user] %>
					<li><%= link_to 'Edit info?', user_edit_path %></li>
					<li><%= link_to 'Edit tags?', user_tags_path %></li>
					<li><%= link_to 'Edit works?', user_works_path %></li>
					<% else %>
					<li><%= link_to "Message", compose_to_path(@vuser[:handle]), :class => "white"%></li>
					<% end %>
				</ul>
        <% end %>
			</div>
		</div>
		<div id="workinfo">
			<h2>Works</h2>
			<div id="userworklist_repop">
			<%= render :partial => "workslist", :locals => {:works => @vuser.works, :edit => false, :ratable => true} %>
			</div>
		</div>
	</div>
<% else %>
	<h2>Whoops!</h2>
	<p> This person doesn't exist! May I suggest you use the search bar.</p>
<% end %>

app/views/user/works.html.erb
<% if @user %>
	<%= link_to "<-- Back to Profile", user_name_path(@user[:handle]), :class =>"back"  %>

	<div id="editworks">
	<h3>Edit works</h3>

	<div id="worklist">
		<!-- <h3>Works</h3> -->
		<%= render :partial => "workslist", :locals => {:works => @user.works, :edit => true, :ratable => false} %>
	</div>
	<div id="workeditform">
		<%= form_tag({:action => :works}, :method => "post") %>
			<table>
				<tr><th colspan="2">Add Work</th></tr>
				<tr><td>Name:</td><td><%= text_field_tag :name %> </td></tr>
				<tr><td>URL:</td><td><%= text_field_tag :url %> </td></tr>
				<tr><td>Decription:</td><td><%= text_area_tag :description %> </td></tr>
				<tr><td>Tags(comma delimited):</td><td><%= text_field_tag :tags%> </td></tr>
			</table>
			<%= submit_tag "Add" %>
		</form>
	</div>
</div>
<% else %>
	<em>You have come here in error</em>
<% end %>