config/routes.rb
Importrequire::Application.routes.draw do

	match "register" => "User#create", :as => "register"
	match "logout" => "welcome#logout", :as => "logout"
	match "login" => "welcome#login", :as => "login"
	match "search" => "search#search", :as => "search"
	match "help" => "help#help", :as => "help"
  match "inbox" => "message#inbox", :as =>"inbox"
  match "inbox/compose" => "message#compose", :as =>"compose"
  match "inbox/compose/:handle" => "message#compose", :as =>"compose_to"
  match "inbox/create_mail" => "message#create_mail", :as =>"create_mail"
  match "inbox/:mid" => "message#view", :as =>"view_mail"
  match "inbox/:mid/reply" => "message#reply", :as =>"reply_mail"
  match "inbox/:mid/unread" => "message#unread", :as =>"unread_mail"
  match "inbox/:mid/delete" => "message#delete", :as =>"delete_mail"
	match ":handle/works/:wid/rate/:rating" => "User#rate_work", :as => "user_rate_work"
	match ":handle/works/create_work" => "User#create_work", :as => "user_create_work"
	match ":handle/works/remove_work/:wid" => "User#remove_work", :as => "user_remove_work"
	match ":handle/works/edit_work/:wid" => "User#edit_work", :as => "user_edit_work"
	match ":handle/works" => "User#works", :as => "user_works"
	match ":handle/edit/create_affil" => "User#create_affil", :as => "user_create_affil"
	match ":handle/edit/remove_affil/:name" => "User#remove_affil", :as => "user_remove_affil"
	match ":handle/edit/create_tag" => "User#create_tag", :as => "user_create_tag"
	match ":handle/edit/remove_tag/:id" => "User#remove_tag", :as => "user_remove_tag"
	match ":handle/edit/remove_all_tags" => "User#remove_all_tags", :as => "user_remove_all_tags"
	match ":handle/tags" => "User#edit_tags", :as => "user_tags"
	match ":handle/edit" => "User#edit", :as => "user_edit"
	match ":handle" => "User#view", :as => "user_name"

   root :to => "welcome#index"

end

app/views/layouts/application.html.erb
<% require_dependency 'gravatar' %>
<!DOCTYPE html>
<html>
<head>
  <title>import::require</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'application','controls', 'dragdrop', 'effects', 'prototype', 'rails' %>
  <%= csrf_meta_tag %>
  <link rel="icon" href="/images/favicon.ico" type="image/x-icon">
  <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">
</head>
<body>

<h1>import::require</h1>
<div id="banner" class="rounded5">
  <a href="/" class=logo_link><img src="/images/blank.png"/></a>
  <div id="search_box">
    <%= form_tag(search_path, :method => "post") %>
    <%= text_field_tag :search_query, nil, :size => 15, :value => "Search", :onfocus => "this.value='';"%> 
    <%= submit_tag '?', :class => "headerbutton" %>
    </form>
  </div>
  <div id="logwelcome">
  <% if session[:user] %>                                          
    <p> Welcome, <%=link_to session[:user], user_name_path(session[:user]), :class => "unametop" %> 
    (<%=link_to "Inbox#{unread_mail(session[:user])}", inbox_path(), :class => "top" %>|<%=link_to "Logout?", logout_path, :class => "top" %>)</p>
  <% else %>
    <%= form_tag(login_path, :method => "post") %>
    <%= text_field_tag :handle, nil, :size => 5, :value => "Handle", :onclick => "this.value='';" %> 
    <%= password_field :pass, nil, :size => 5, :value => "Password", :onclick => "this.value='';"  %> 
    <%= hidden_field_tag :ocontroller, params[:controller] %> 
    <%= hidden_field_tag :oaction, params[:action] %> 
    <%= submit_tag 'Login', :class => "headerbutton" %>
    </form>
    <!--<p class="top_reg">New User? <%= link_to "Register", register_path, :class =>"white" %></p>-->
  <% end %>
  </div>
</div>

<% if flash[:notice] %>
<div id="notice" onclick="this.style.display='none';">
	<p><%=flash[:notice]%></p>
	<% flash[:notice] = nil %>
</div>
<% end %>

<div id="content" class="rounded5">
<%= yield %>
</div>

<br/>
<hr/>
<div id="footer" class="rounded5">
<p>import::require &copy; 2011
| 
<a href="http://importrequire.wordpress.com" target="_blank">blog</a>
|
<%= link_to "help", help_path %>
|
<iframe src="http://www.facebook.com/plugins/like.php?app_id=109276079159107&amp;href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FImportrequire%2F188212911208549&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=true&amp;action=recommend&amp;colorscheme=light&amp;font=verdana&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:98px; height:21px;margin:0" allowTransparency="true"></iframe>
|
<a href="http://www.twitter.com/importrequire" target="_blank"><img src="http://twitter-badges.s3.amazonaws.com/twitter-a.png" alt="Follow importrequire on Twitter" height="21px"/></a>
|
<img src="http://l.yimg.com/hr/img/delicious.small.gif" height="20" width="20" alt="Delicious" />
<a href="http://www.delicious.com/save" onclick="window.open('http://www.delicious.com/save?v=5&noui&jump=close&url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title), 'delicious','toolbar=no,width=550,height=550'); return false;"> Bookmark this on Delicious</a>
</div>

</body>
</html>